application:
  name: '@project.artifactId@'
build:
  version: '@project.version@'

server:
  port: ${APPLICATION_PORT:8087}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5410/test-db
    username: user
    password: user

logging:
  expiration-time:
    months: 1